"""empty message

Revision ID: 3e7b1f83f88b
Revises: 469adf0c35b5
Create Date: 2020-06-24 13:03:41.232163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7b1f83f88b'
down_revision = '469adf0c35b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category', sa.String(length=25), nullable=True))
    op.add_column('post', sa.Column('eventdate', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    op.drop_column('post', 'eventdate')
    op.drop_column('post', 'category')
    # ### end Alembic commands ###
